#!/opt/homebrew/bin/bash
#!/usr/local/bin/bash
#!/bin/bash

#bash-scripts validations
BS_DIR=./bash-scripts
if [ ! -d "$BS_DIR" ]; then
    git clone https://github.com/Michaelv55/bash-scripts.git
else
    echo "repo bash-scripts updating...";
    git -C ./bash-scripts pull
fi

#os validations
OS=$("$BS_DIR/getOs.sh")
if [[ $OS -eq "OSX" ]]; then
    if [[ $(command -v brew) == "" ]]; then
        echo "Brew not installed. Brew is required to continue the process on $OS."
        exit 1
    fi
    if [[ `brew list -1 | grep "gnu-getopt"` != "gnu-getopt" ]]; then
        echo "gnu-getopt is required. use: 'brew install gnu-getopt'"
        echo "Then follow directions from brew to add to your local path: echo 'export PATH= \"/opt/homebrew/opt/gnu-getopt/bin:\$PATH\" >> ~/.zshrc"
        exit 1
    fi
fi

BASH_V=`echo $BASH_VERSION | cut -c1-1`;
if [[ "$BASH_V" -lt 4 ]]; then
    echo "Bash version 4 or higher is required. Actual version $BASH_VERSION"
    echo "use: 'brew upgrade' and then 'brew install bash'"
    echo "open with vim /etc/shells and add hombrew bash route (which -a bash): '/opt/homebrew/bin/bash'"
    echo "set default shell: sudo chsh -s /opt/homebrew/bin/bash"
    echo "restart terminal and test 'bash --version'"
    exit 1
fi

DIR_DEVTOOLS=./vendor/phalcon/devtools
if [ ! -d "$DIR_DEVTOOLS" ]; then
    echo $'\n'
    echo "phalcon devtools not installed local"
    echo "install phalcon devtools from 'composer require phalcon/devtools --dev'"
    echo $'\n'
    exit 1
fi

OPTION="$1"
case $OPTION in
    "info"|"i") "$DIR_DEVTOOLS"/phalcon $1 ;;
    "commands"|"list"|"enumerate") "$DIR_DEVTOOLS"/phalcon $1 ;;
    "controller"|"create-controller") "$DIR_DEVTOOLS"/phalcon $@ ;;
    "module") "$DIR_DEVTOOLS"/phalcon $@ ;;
    "model") "$DIR_DEVTOOLS"/phalcon $@ ;;
    "all-models") "$DIR_DEVTOOLS"/phalcon $@ ;;
    "project") "$DIR_DEVTOOLS"/phalcon $@ ;;
    "scaffold") "$DIR_DEVTOOLS"/phalcon $@ ;;
    "migration") "$DIR_DEVTOOLS"/phalcon $@ ;;
    "webtools") "$DIR_DEVTOOLS"/phalcon $@ ;;
    "serve") "$DIR_DEVTOOLS"/phalcon $@ ;;
    "console") "$DIR_DEVTOOLS"/phalcon $1 ;;
    *) "$DIR_DEVTOOLS"/phalcon $@ ;;
esac